### ISSUE TITLE
Is nnlr + optim multiplying the base lr twice?

### ISSUE THREAD

**Issue by jimxinbo** [gpleiss/nnlr#3]
Hi, let me know if I am wrong but it seems in optim/sgd.lua, we have 

   _local clr = lr / (1 + nevals*lrd)
   if lrs then
      if not state.deltaParameters then
         state.deltaParameters = torch.Tensor():typeAs(x):resizeAs(dfdx)
      end
      state.deltaParameters:copy(lrs):cmul(dfdx)
      x:add(-clr, state.deltaParameters)
   else
      x:add(-clr, dfdx)
   end_

where copy(lrs):cmul(dfdx) and x:add(-clr,state.deltaParameters) seem to be multiplying dfdx with both lrs and clr (which is effectively base lr), therefore if base lr is already multiplied to lrs as did in nnlr, are we essentially multiplying the base lr twice?

**Comment by gpleiss** [comment]
Ah shoot, you are right. I think the fix would be [here](https://github.com/gpleiss/nnlr/blob/master/nnlr.lua#L57-L63) - removing the line that multiplies `weightLearningRates` and `biasLearningRates` by `baseLearningRate`.

I will try to fix this soon. Or if you would like, I will gladly accept a PR.

**Comment by jimxinbo** [comment]
Good to know. Yeah, I agree the fix should be easy as you suggested. Sure, I am glad to pull a request. 
Anyway, this is a useful package, thanks.

**Comment by gpleiss** [comment]
Resolved by #5
