### ISSUE TITLE
Whether to support other optimization algorithms except SGD

### ISSUE THREAD

**Issue by LinZhineng** [gpleiss/nnlr#8]
hi,
I found that adam optimization algorithm does not have "learningRates" parameter, but the SGD algorithm has this parameter. Now is not yet support the adam optimization algorithm?

reference: 
1. https://github.com/torch/optim/blob/master/adam.lua
2. https://github.com/torch/optim/blob/master/sgd.lua

**Comment by gpleiss** [comment]
Yeah, I think SGD is the only algorithm that supports the multiple learning rates. The adam optimizer in the optim package would need to be updated first before other algorithms could be supported.
